package com.kpleasing.wxss.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbBankInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_bank_info", catalog = "wxss")
public class BankInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 4125020155781958424L;
	private Integer userId;
	private String repayAccBank;
	private String repayAccBankCode;
	private String repayCardNo;
	private String bankPhone;
	private String bankcardFrontImagePath;
	private String bankcardBackImagePath;
	private String token;
	private String storablePan;
	private String smsSendtime;
	private String externalNo;
	private String spdbVerifyCode;
	private byte spdbFlag;
	private String spdbUuid;
	private String spdbAccountId;
	private Date spdbOpenAccountTime;
	private String spdbAccountType;
	private String spdbStcardNo;
	private String spdbCertCode;

	public BankInfo() {
	}

	public BankInfo(Integer userId) {
		this.userId = userId;
	}

	public BankInfo(Integer userId, String repayAccBank, String repayAccBankCode, String repayCardNo, String bankPhone,
			String bankcardFrontImagePath, String bankcardBackImagePath, String token, String storablePan,
			String smsSendtime) {
		this.userId = userId;
		this.repayAccBank = repayAccBank;
		this.repayAccBankCode = repayAccBankCode;
		this.repayCardNo = repayCardNo;
		this.bankPhone = bankPhone;
		this.bankcardFrontImagePath = bankcardFrontImagePath;
		this.bankcardBackImagePath = bankcardBackImagePath;
		this.token = token;
		this.storablePan = storablePan;
		this.smsSendtime = smsSendtime;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "repay_acc_bank", length = 20)
	public String getRepayAccBank() {
		return this.repayAccBank;
	}

	public void setRepayAccBank(String repayAccBank) {
		if(null!=repayAccBank) {
			this.repayAccBank = repayAccBank.replaceAll("\\s", "");
		} else {
			this.repayAccBank = repayAccBank;
		}
	}

	@Column(name = "repay_acc_bank_code", length = 20)
	public String getRepayAccBankCode() {
		return this.repayAccBankCode;
	}

	public void setRepayAccBankCode(String repayAccBankCode) {
		if(null!=repayAccBankCode) {
			this.repayAccBankCode = repayAccBankCode.replaceAll("\\s", "");
		} else {
			this.repayAccBankCode = repayAccBankCode;
		}
	}

	@Column(name = "repay_card_no", length = 20)
	public String getRepayCardNo() {
		return this.repayCardNo;
	}

	public void setRepayCardNo(String repayCardNo) {
		if(null!=repayCardNo) {
			this.repayCardNo = repayCardNo.replaceAll("\\s", "");
		} else {
			this.repayCardNo = repayCardNo;
		}
	}

	@Column(name = "bank_phone", length = 11)
	public String getBankPhone() {
		return this.bankPhone;
	}

	public void setBankPhone(String bankPhone) {
		if(null!=bankPhone) {
			this.bankPhone = bankPhone.replaceAll("\\s", "");
		} else {
			this.bankPhone = bankPhone;
		}
	}

	@Column(name = "bankcard_front_image_path", length = 256)
	public String getBankcardFrontImagePath() {
		return this.bankcardFrontImagePath;
	}

	public void setBankcardFrontImagePath(String bankcardFrontImagePath) {
		this.bankcardFrontImagePath = bankcardFrontImagePath;
	}

	@Column(name = "bankcard_back_image_path", length = 256)
	public String getBankcardBackImagePath() {
		return this.bankcardBackImagePath;
	}

	public void setBankcardBackImagePath(String bankcardBackImagePath) {
		this.bankcardBackImagePath = bankcardBackImagePath;
	}

	@Column(name = "token", length = 30)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "storable_pan", length = 20)
	public String getStorablePan() {
		return this.storablePan;
	}

	public void setStorablePan(String storablePan) {
		this.storablePan = storablePan;
	}

	@Column(name = "sms_sendtime", length = 20)
	public String getSmsSendtime() {
		return this.smsSendtime;
	}

	public void setSmsSendtime(String smsSendtime) {
		this.smsSendtime = smsSendtime;
	}
	
	@Column(name = "external_no", length = 32)
	public String getExternalNo() {
		return this.externalNo;
	}

	public void setExternalNo(String externalNo) {
		this.externalNo = externalNo;
	}

	@Column(name = "spdb_verify_code", length = 10)
	public String getSpdbVerifyCode() {
		return spdbVerifyCode;
	}

	public void setSpdbVerifyCode(String spdbVerifyCode) {
		this.spdbVerifyCode = spdbVerifyCode;
	}

	@Column(name = "spdb_flag", nullable = false)
	public byte getSpdbFlag() {
		return spdbFlag;
	}

	public void setSpdbFlag(byte spdbFlag) {
		this.spdbFlag = spdbFlag;
	}

	@Column(name = "spdb_uuid", length = 256)
	public String getSpdbUuid() {
		return spdbUuid;
	}

	public void setSpdbUuid(String spdbUuid) {
		this.spdbUuid = spdbUuid;
	}

	@Column(name = "spdb_accountId", length = 256)
	public String getSpdbAccountId() {
		return spdbAccountId;
	}

	public void setSpdbAccountId(String spdbAccountId) {
		this.spdbAccountId = spdbAccountId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "spdb_open_account_time", length = 19)
	public Date getSpdbOpenAccountTime() {
		return spdbOpenAccountTime;
	}

	public void setSpdbOpenAccountTime(Date spdbOpenAccountTime) {
		this.spdbOpenAccountTime = spdbOpenAccountTime;
	}

	@Column(name = "spdb_account_type", length = 8)
	public String getSpdbAccountType() {
		return spdbAccountType;
	}

	public void setSpdbAccountType(String spdbAccountType) {
		this.spdbAccountType = spdbAccountType;
	}

	@Column(name = "spdb_stcard_no", length = 255)
	public String getSpdbStcardNo() {
		return spdbStcardNo;
	}

	public void setSpdbStcardNo(String spdbStcardNo) {
		this.spdbStcardNo = spdbStcardNo;
	}

	@Column(name = "spdb_cert_code", length = 20)
	public String getSpdbCertCode() {
		return spdbCertCode;
	}

	public void setSpdbCertCode(String spdbCertCode) {
		this.spdbCertCode = spdbCertCode;
	}
}
