package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCar generated by hbm2java
 */
@Entity
@Table(name = "tb_car", catalog = "wxss")
public class Car implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 5908254797072090307L;
	private Integer id;
	private int modelId;
	private String firstLetter;
	private String brand;
	private String series;
	private String seriesLogo;
	private String model;
	private String saleStatus;
	private String menufactory;
	private String year;
	private String publicTime;
	private String msrp;
	private String modelType;
	private byte enabledFlag;
	private Date createAt;
	private Date updateAt;
	private String remark;

	public Car() {
	}

	public Car(int modelId, Date createAt) {
		this.modelId = modelId;
		this.createAt = createAt;
	}

	public Car(int modelId, String firstLetter, String brand, String series, String seriesLogo, String model,
			String saleStatus, String menufactory, String year, String publicTime, String msrp, String modelType,
			byte enabledFlag, Date createAt, Date updateAt, String remark) {
		this.modelId = modelId;
		this.firstLetter = firstLetter;
		this.brand = brand;
		this.series = series;
		this.seriesLogo = seriesLogo;
		this.model = model;
		this.saleStatus = saleStatus;
		this.menufactory = menufactory;
		this.year = year;
		this.publicTime = publicTime;
		this.msrp = msrp;
		this.modelType = modelType;
		this.enabledFlag = enabledFlag;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "model_id", nullable = false)
	public int getModelId() {
		return this.modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@Column(name = "first_letter", length = 10)
	public String getFirstLetter() {
		return this.firstLetter;
	}

	public void setFirstLetter(String firstLetter) {
		this.firstLetter = firstLetter;
	}

	@Column(name = "brand", length = 20)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "series", length = 60)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "series_logo", length = 60)
	public String getSeriesLogo() {
		return this.seriesLogo;
	}

	public void setSeriesLogo(String seriesLogo) {
		this.seriesLogo = seriesLogo;
	}

	@Column(name = "model", length = 60)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "sale_status", length = 20)
	public String getSaleStatus() {
		return this.saleStatus;
	}

	public void setSaleStatus(String saleStatus) {
		this.saleStatus = saleStatus;
	}

	@Column(name = "menufactory", length = 60)
	public String getMenufactory() {
		return this.menufactory;
	}

	public void setMenufactory(String menufactory) {
		this.menufactory = menufactory;
	}

	@Column(name = "year", length = 20)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "public_time", length = 20)
	public String getPublicTime() {
		return this.publicTime;
	}

	public void setPublicTime(String publicTime) {
		this.publicTime = publicTime;
	}

	@Column(name = "msrp", length = 20)
	public String getMsrp() {
		return this.msrp;
	}

	public void setMsrp(String msrp) {
		this.msrp = msrp;
	}

	@Column(name = "model_type", length = 20)
	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", nullable = false, length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "enabled_flag", nullable = false)
	public byte getEnabledFlag() {
		return this.enabledFlag;
	}

	public void setEnabledFlag(byte enabledFlag) {
		this.enabledFlag = enabledFlag;
	}
	
}
