package com.kpleasing.wxss.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCarConfig generated by hbm2java
 */
@Entity
@Table(name = "tb_car_param", catalog = "wxss")
public class CarParam implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 2523856224249617489L;
	private Integer id;
	private int modelId;
	private String modelParamName;
	private String modelParamValue;

	public CarParam() {
	}

	public CarParam(int modelId, String modelParamName, String modelParamValue) {
		this.modelId = modelId;
		this.modelParamName = modelParamName;
		this.modelParamValue = modelParamValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "model_id", nullable = false)
	public int getModelId() {
		return this.modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@Column(name = "model_param_name", nullable = false, length = 60)
	public String getModelParamName() {
		return this.modelParamName;
	}

	public void setModelParamName(String modelParamName) {
		this.modelParamName = modelParamName;
	}

	@Column(name = "model_param_value", nullable = false)
	public String getModelParamValue() {
		return this.modelParamValue;
	}

	public void setModelParamValue(String modelParamValue) {
		this.modelParamValue = modelParamValue;
	}

}
