package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CertInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_cert_info")
public class CertInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = -5488859300593066812L;
	private int userId;
	private String userName;
	private String gender;
	private String genderCode;
	private String nation;
	private Date birthday;
	private String liveAddr;
	private String certType;
	private String certId;
	private String certAddr;
	private String certFrontImagePath;
	private String certBackImagePath;

	public CertInfo() {
		this.certType = "ID_CARD";
	}

	public CertInfo(int userId, String userName, String gender, String genderCode, String nation, Date birthday, String liveAddr,
			String certType, String certId) {
		this.userId = userId;
		this.userName = userName;
		this.gender = gender;
		this.genderCode = genderCode;
		this.nation = nation;
		this.birthday = birthday;
		this.liveAddr = liveAddr;
		this.certType = certType;
		this.certId = certId;
	}

	public CertInfo(int userId, String userName, String gender, String genderCode, String nation, Date birthday, String liveAddr,
			String certType, String certId, String certAddr, String certFrontImagePath, String certBackImagePath) {
		this.userId = userId;
		this.userName = userName;
		this.gender = gender;
		this.genderCode = genderCode;
		this.nation = nation;
		this.birthday = birthday;
		this.liveAddr = liveAddr;
		this.certType = certType;
		this.certId = certId;
		this.certAddr = certAddr;
		this.certFrontImagePath = certFrontImagePath;
		this.certBackImagePath = certBackImagePath;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "gender_code", length = 20)
	public String getGenderCode() {
		return genderCode;
	}

	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

	@Column(name = "nation", length = 10)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "live_addr", length = 100)
	public String getLiveAddr() {
		return this.liveAddr;
	}

	public void setLiveAddr(String liveAddr) {
		this.liveAddr = liveAddr;
	}

	@Column(name = "cert_type", length = 10)
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "cert_id", length = 18)
	public String getCertId() {
		return this.certId;
	}

	public void setCertId(String certId) {
		this.certId = certId;
	}

	@Column(name = "cert_addr")
	public String getCertAddr() {
		return this.certAddr;
	}

	public void setCertAddr(String certAddr) {
		this.certAddr = certAddr;
	}

	@Column(name = "cert_front_image_path", length = 60)
	public String getCertFrontImagePath() {
		return this.certFrontImagePath;
	}

	public void setCertFrontImagePath(String certFrontImagePath) {
		this.certFrontImagePath = certFrontImagePath;
	}

	@Column(name = "cert_back_image_path", length = 60)
	public String getCertBackImagePath() {
		return this.certBackImagePath;
	}

	public void setCertBackImagePath(String certBackImagePath) {
		this.certBackImagePath = certBackImagePath;
	}

}
