package com.kpleasing.wxss.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbContactInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_contact_info", catalog = "wxss")
public class ContactInfo implements java.io.Serializable {

	/** * */
	private static final long serialVersionUID = -2367680752288807275L;
	private int userId;
	private String spouseName;
	private String spouseCertType;
	private String spouseCertId;
	private String spousePhone;
	private String spouseAnnualIncome;
	private String spouseAnnualIncomeCode;
	private String spouseIncomeFrom;
	private String spouseIncomeFromCode;
	private String spouseWorkUnit;
	private String contactRelation;
	private String contactRelationCode;
	private String contactName;
	private String contactCertType;
	private String contactCertId;
	private String contactPhone;
	private String contact2Relation;
	private String contact2RelationCode;
	private String contact2Name;
	private String contact2CertType;
	private String contact2CertId;
	private String contact2Phone;

	public ContactInfo() {
		this.spouseCertType = "ID_CARD";
		this.contactCertType = "ID_CARD";
		this.contact2CertType = "ID_CARD";
	}

	public ContactInfo(int userId) {
		this.userId = userId;
	}

	public ContactInfo(int userId, String spouseName, String spouseCertType, String spouseCertId, String spousePhone,
			String spouseAnnualIncome, String spouseAnnualIncomeCode, String spouseIncomeFrom,
			String spouseIncomeFromCode, String spouseWorkUnit, String contactRelation, String contactRelationCode,
			String contactName, String contactCertType, String contactCertId, String contactPhone,
			String contact2Relation, String contact2RelationCode, String contact2Name, String contact2CertType,
			String contact2CertId, String contact2Phone) {
		this.userId = userId;
		this.spouseName = spouseName;
		this.spouseCertType = spouseCertType;
		this.spouseCertId = spouseCertId;
		this.spousePhone = spousePhone;
		this.spouseAnnualIncome = spouseAnnualIncome;
		this.spouseAnnualIncomeCode = spouseAnnualIncomeCode;
		this.spouseIncomeFrom = spouseIncomeFrom;
		this.spouseIncomeFromCode = spouseIncomeFromCode;
		this.spouseWorkUnit = spouseWorkUnit;
		this.contactRelation = contactRelation;
		this.contactRelationCode = contactRelationCode;
		this.contactName = contactName;
		this.contactCertType = contactCertType;
		this.contactCertId = contactCertId;
		this.contactPhone = contactPhone;
		this.contact2Relation = contact2Relation;
		this.contact2RelationCode = contact2RelationCode;
		this.contact2Name = contact2Name;
		this.contact2CertType = contact2CertType;
		this.contact2CertId = contact2CertId;
		this.contact2Phone = contact2Phone;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "spouse_name", length = 10)
	public String getSpouseName() {
		return this.spouseName;
	}

	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName;
	}

	@Column(name = "spouse_cert_type", length = 10)
	public String getSpouseCertType() {
		return this.spouseCertType;
	}

	public void setSpouseCertType(String spouseCertType) {
		this.spouseCertType = spouseCertType;
	}

	@Column(name = "spouse_cert_id", length = 18)
	public String getSpouseCertId() {
		return this.spouseCertId;
	}

	public void setSpouseCertId(String spouseCertId) {
		this.spouseCertId = spouseCertId;
	}

	@Column(name = "spouse_phone", length = 11)
	public String getSpousePhone() {
		return this.spousePhone;
	}

	public void setSpousePhone(String spousePhone) {
		this.spousePhone = spousePhone;
	}

	@Column(name = "spouse_annual_income", length = 20)
	public String getSpouseAnnualIncome() {
		return this.spouseAnnualIncome;
	}

	public void setSpouseAnnualIncome(String spouseAnnualIncome) {
		this.spouseAnnualIncome = spouseAnnualIncome;
	}

	@Column(name = "spouse_annual_income_code", length = 20)
	public String getSpouseAnnualIncomeCode() {
		return this.spouseAnnualIncomeCode;
	}

	public void setSpouseAnnualIncomeCode(String spouseAnnualIncomeCode) {
		this.spouseAnnualIncomeCode = spouseAnnualIncomeCode;
	}

	@Column(name = "spouse_income_from", length = 20)
	public String getSpouseIncomeFrom() {
		return this.spouseIncomeFrom;
	}

	public void setSpouseIncomeFrom(String spouseIncomeFrom) {
		this.spouseIncomeFrom = spouseIncomeFrom;
	}

	@Column(name = "spouse_income_from_code", length = 20)
	public String getSpouseIncomeFromCode() {
		return this.spouseIncomeFromCode;
	}

	public void setSpouseIncomeFromCode(String spouseIncomeFromCode) {
		this.spouseIncomeFromCode = spouseIncomeFromCode;
	}

	@Column(name = "spouse_work_unit", length = 60)
	public String getSpouseWorkUnit() {
		return this.spouseWorkUnit;
	}

	public void setSpouseWorkUnit(String spouseWorkUnit) {
		this.spouseWorkUnit = spouseWorkUnit;
	}

	@Column(name = "contact_relation", length = 20)
	public String getContactRelation() {
		return this.contactRelation;
	}

	public void setContactRelation(String contactRelation) {
		this.contactRelation = contactRelation;
	}

	@Column(name = "contact_relation_code", length = 20)
	public String getContactRelationCode() {
		return this.contactRelationCode;
	}

	public void setContactRelationCode(String contactRelationCode) {
		this.contactRelationCode = contactRelationCode;
	}

	@Column(name = "contact_name", length = 10)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_cert_type", length = 10)
	public String getContactCertType() {
		return this.contactCertType;
	}

	public void setContactCertType(String contactCertType) {
		this.contactCertType = contactCertType;
	}

	@Column(name = "contact_cert_id", length = 18)
	public String getContactCertId() {
		return this.contactCertId;
	}

	public void setContactCertId(String contactCertId) {
		this.contactCertId = contactCertId;
	}

	@Column(name = "contact_phone", length = 11)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "contact2_relation", length = 20)
	public String getContact2Relation() {
		return this.contact2Relation;
	}

	public void setContact2Relation(String contact2Relation) {
		this.contact2Relation = contact2Relation;
	}

	@Column(name = "contact2_relation_code", length = 20)
	public String getContact2RelationCode() {
		return this.contact2RelationCode;
	}

	public void setContact2RelationCode(String contact2RelationCode) {
		this.contact2RelationCode = contact2RelationCode;
	}

	@Column(name = "contact2_name", length = 10)
	public String getContact2Name() {
		return this.contact2Name;
	}

	public void setContact2Name(String contact2Name) {
		this.contact2Name = contact2Name;
	}

	@Column(name = "contact2_cert_type", length = 10)
	public String getContact2CertType() {
		return this.contact2CertType;
	}

	public void setContact2CertType(String contact2CertType) {
		this.contact2CertType = contact2CertType;
	}

	@Column(name = "contact2_cert_id", length = 18)
	public String getContact2CertId() {
		return this.contact2CertId;
	}

	public void setContact2CertId(String contact2CertId) {
		this.contact2CertId = contact2CertId;
	}

	@Column(name = "contact2_phone", length = 11)
	public String getContact2Phone() {
		return this.contact2Phone;
	}

	public void setContact2Phone(String contact2Phone) {
		this.contact2Phone = contact2Phone;
	}

}
