package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrivingLicenseInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_driving_license_info")
public class DrivingLicenseInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = -2918512241663360506L;
	private int userId;
	private String driveType;
	private String driveTypeDesc;
	private Date driveFirstDate;
	private String driveImagePath;
	private String driveBackImagePath;

	public DrivingLicenseInfo() {
	}

	public DrivingLicenseInfo(int userId, String driveType, String driveTypeDesc, Date driveFirstDate,
			String driveImagePath, String driveBackImagePath) {
		this.userId = userId;
		this.driveType = driveType;
		this.driveTypeDesc = driveTypeDesc;
		this.driveFirstDate = driveFirstDate;
		this.driveImagePath = driveImagePath;
		this.driveBackImagePath = driveBackImagePath;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "drive_type", length = 10)
	public String getDriveType() {
		return this.driveType;
	}

	public void setDriveType(String driveType) {
		if(null!=driveType) {
			this.driveType = driveType.replaceAll("\\s", "");
		} else {
			this.driveType = driveType;
		}
	}

	@Column(name = "drive_type_desc", length = 20)
	public String getDriveTypeDesc() {
		return this.driveTypeDesc;
	}

	public void setDriveTypeDesc(String driveTypeDesc) {
		if(null!=driveTypeDesc) {
			this.driveTypeDesc = driveTypeDesc.replaceAll("\\s", "");
		} else {
			this.driveTypeDesc = driveTypeDesc;
		}
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "drive_first_date", length = 10)
	public Date getDriveFirstDate() {
		return this.driveFirstDate;
	}

	public void setDriveFirstDate(Date driveFirstDate) {
		this.driveFirstDate = driveFirstDate;
	}

	@Column(name = "drive_image_path", length = 60)
	public String getDriveImagePath() {
		return this.driveImagePath;
	}

	public void setDriveImagePath(String driveImagePath) {
		this.driveImagePath = driveImagePath;
	}

	@Column(name = "drive_back_image_path", length = 60)
	public String getDriveBackImagePath() {
		return driveBackImagePath;
	}

	public void setDriveBackImagePath(String driveBackImagePath) {
		this.driveBackImagePath = driveBackImagePath;
	}

}
