package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbFaceVideo generated by hbm2java
 */
@Entity
@Table(name = "tb_face_video", catalog = "wxss")
public class FaceVideo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 3577276809070472006L;
	private Integer custId;
	private String custName;
	private String firstDate;
	private String secondDate;
	private String spName;
	private String scheme;
	private String brand;
	private String series;
	private String seriesLogo;
	private String model;
	private Date createAt;
	private Date updateAt;
	private String remark;

	public FaceVideo() {
	}

	public FaceVideo(Integer custId) {
		this.custId = custId;
	}

	public FaceVideo(Integer custId, String custName, String firstDate, String secondDate, String spName, String scheme, 
			String brand, String series, String seriesLogo, String model, Date createAt, Date updateAt, String remark) {
		this.custId = custId;
		this.custName = custName;
		this.firstDate = firstDate;
		this.secondDate = secondDate;
		this.spName = spName;
		this.scheme = scheme;
		this.brand = brand;
		this.series = series;
		this.seriesLogo = seriesLogo;
		this.model = model;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.remark = remark;
	}

	@Id
	@Column(name = "cust_id", unique = true, nullable = false)
	public int getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	@Column(name = "cust_name", length = 20)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "first_date", length = 20)
	public String getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(String firstDate) {
		this.firstDate = firstDate;
	}

	@Column(name = "second_date", length = 20)
	public String getSecondDate() {
		return this.secondDate;
	}

	public void setSecondDate(String secondDate) {
		this.secondDate = secondDate;
	}

	@Column(name = "sp_name", length = 60)
	public String getSpName() {
		return this.spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}
	
	@Column(name = "scheme", length = 255)
	public String getScheme() {
		return this.scheme;
	}

	public void setScheme(String scheme) {
		this.scheme = scheme;
	}

	@Column(name = "brand", length = 20)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "series", length = 60)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "series_logo", length = 60)
	public String getSeriesLogo() {
		return this.seriesLogo;
	}

	public void setSeriesLogo(String seriesLogo) {
		this.seriesLogo = seriesLogo;
	}

	@Column(name = "model", length = 60)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
