package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/** 
 * Order generated by hbm2java
 */
@Entity
@Table(name = "tb_order")
public class Order implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 2971834119776082447L;
	private Integer orderId;
	private Integer bpId;
	private String bpCode;
	private Integer planId;
	private Integer saleId;
	private Integer custId;
	private String userName;
	private String phone;
	private String certType;
	private String certId;
	private String wxOpenId;
	private byte stepNo;
	private byte status;
	private byte loginChannel;
	private Date createAt;
	private Date updateAt;
	private String remark;
	private CertInfo certInfo;
	private DrivingLicenseInfo drivingLicenseInfo;
	private BankInfo bankInfo;
	private PersonInfo personInfo;
	private ContactInfo contactInfo;
	private WorkInfo workInfo;

	public Order() {
		this.certType = "ID_CARD";
	}

	public Order(String phone, byte stepNo, byte status, Date createAt) {
		this.phone = phone;
		this.stepNo = stepNo;
		this.status = status;
		this.createAt = createAt;
	}

	public Order(Integer bpId, Integer custId, String userName, String phone, String certType, String certId,
			String wxOpenId, byte stepNo, byte status, Date createAt, Date updateAt, String remark) {
		this.bpId = bpId;
		this.custId = custId;
		this.userName = userName;
		this.phone = phone;
		this.certType = certType;
		this.certId = certId;
		this.wxOpenId = wxOpenId;
		this.stepNo = stepNo;
		this.status = status;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "bp_id")
	public Integer getBpId() {
		return bpId;
	}

	public void setBpId(Integer bpId) {
		this.bpId = bpId;
	}

	@Column(name = "bp_code")
	public String getBpCode() {
		return bpCode;
	}

	public void setBpCode(String bpCode) {
		this.bpCode = bpCode;
	}

	@Column(name = "plan_id")
	public Integer getPlanId() {
		return planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	@Column(name = "sale_id")
	public Integer getSaleId() {
		return saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
	}

	@Column(name = "cust_id")
	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "phone", nullable = false, length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "cert_type", length = 10)
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "cert_id", length = 18)
	public String getCertId() {
		return this.certId;
	}

	public void setCertId(String certId) {
		this.certId = certId;
	}

	@Column(name = "wx_open_id", length = 32)
	public String getWxOpenId() {
		return this.wxOpenId;
	}

	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId;
	}

	@Column(name = "step_no", nullable = false)
	public byte getStepNo() {
		return this.stepNo;
	}

	public void setStepNo(byte stepNo) {
		this.stepNo = stepNo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}
	
	@Column(name = "login_channel", nullable = false)
	public byte getLoginChannel() {
		return this.loginChannel;
	}

	public void setLoginChannel(byte loginChannel) {
		this.loginChannel = loginChannel;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", nullable = false, length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Transient
	public CertInfo getCertInfo() {
		return certInfo;
	}

	public void setCertInfo(CertInfo certInfo) {
		this.certInfo = certInfo;
	}

	@Transient
	public DrivingLicenseInfo getDrivingLicenseInfo() {
		return drivingLicenseInfo;
	}

	public void setDrivingLicenseInfo(DrivingLicenseInfo drivingLicenseInfo) {
		this.drivingLicenseInfo = drivingLicenseInfo;
	}

	@Transient
	public BankInfo getBankInfo() {
		return bankInfo;
	}

	public void setBankInfo(BankInfo bankInfo) {
		this.bankInfo = bankInfo;
	}

	@Transient
	public PersonInfo getPersonInfo() {
		return personInfo;
	}

	public void setPersonInfo(PersonInfo personInfo) {
		this.personInfo = personInfo;
	}

	@Transient
	public ContactInfo getContactInfo() {
		return contactInfo;
	}

	public void setContactInfo(ContactInfo contactInfo) {
		this.contactInfo = contactInfo;
	}
	
	@Transient
	public WorkInfo getWorkInfo() {
		return workInfo;
	}

	public void setWorkInfo(WorkInfo workInfo) {
		this.workInfo = workInfo;
	}
}
