package com.kpleasing.wxss.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPersonInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_person_info", catalog = "wxss")
public class PersonInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 5600051515162546930L;
	private int userId;
	private String userName;
	private String liveStatus;
	private String liveStatusCode;
	private String eduLevel;
	private String eduLevelCode;
	private String province;
	private String city;
	private String familyAddr;
	private String familyPhone;
	private String email;
	private String marrStatus;
	private String marrStatusCode;
	private String spouseName;
	private String spouseCertType;
	private String spouseCertId;
	private String spousePhone;
	private String spouseAnnualIncome;
	private String spouseAnnualIncomeCode;
	private String spouseIncomeFrom;
	private String spouseIncomeFromCode;
	private String spouseWorkUnit;
	private String contactRelation;
	private String contactRelationCode;
	private String contactName;
	private String contactCertType;
	private String contactCertId;
	private String contactPhone;

	public PersonInfo() {
		this.spouseCertType = "ID_CARD";
		this.contactCertType = "ID_CARD";
	}

	public PersonInfo(int userId, String userName, String liveStatus, String liveStatusCode, String eduLevel,
			String eduLevelCode, String familyAddr, String email, String marrStatus, String marrStatusCode) {
		this.userId = userId;
		this.userName = userName;
		this.liveStatus = liveStatus;
		this.liveStatusCode = liveStatusCode;
		this.eduLevel = eduLevel;
		this.eduLevelCode = eduLevelCode;
		this.familyAddr = familyAddr;
		this.email = email;
		this.marrStatus = marrStatus;
		this.marrStatusCode = marrStatusCode;
	}

	public PersonInfo(int userId, String userName, String liveStatus, String liveStatusCode, String eduLevel,
			String eduLevelCode, String familyAddr, String email, String marrStatus, String marrStatusCode,
			String spouseName, String spouseCertType, String spouseCertId, String spousePhone,
			String spouseAnnualIncome, String spouseAnnualIncomeCode, String spouseIncomeFrom, 
			String spouseIncomeFromCode, String spouseWorkUnit, String contactRelation,
			String contactRelationCode, String contactName, String contactCertType, String contactCertId,
			String contactPhone) {
		this.userId = userId;
		this.userName = userName;
		this.liveStatus = liveStatus;
		this.liveStatusCode = liveStatusCode;
		this.eduLevel = eduLevel;
		this.eduLevelCode = eduLevelCode;
		this.familyAddr = familyAddr;
		this.email = email;
		this.marrStatus = marrStatus;
		this.marrStatusCode = marrStatusCode;
		this.spouseName = spouseName;
		this.spouseCertType = spouseCertType;
		this.spouseCertId = spouseCertId;
		this.spousePhone = spousePhone;
		this.spouseAnnualIncome = spouseAnnualIncome;
		this.spouseAnnualIncomeCode = spouseAnnualIncomeCode;
		this.spouseIncomeFrom = spouseIncomeFrom;
		this.spouseIncomeFromCode = spouseIncomeFromCode;
		this.spouseWorkUnit = spouseWorkUnit;
		this.contactRelation = contactRelation;
		this.contactRelationCode = contactRelationCode;
		this.contactName = contactName;
		this.contactCertType = contactCertType;
		this.contactCertId = contactCertId;
		this.contactPhone = contactPhone;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		if(userName != null){
			this.userName = userName.replaceAll("\\s", "");
		}else{
			this.userName = userName;
		}
	}

	@Column(name = "live_status", nullable = false, length = 20)
	public String getLiveStatus() {
		return this.liveStatus;
	}

	public void setLiveStatus(String liveStatus) {
		if(liveStatus != null){
			this.liveStatus = liveStatus.replaceAll("\\s", "");
		}else{
			this.liveStatus = liveStatus;
		}
	}

	@Column(name = "live_status_code", nullable = false, length = 20)
	public String getLiveStatusCode() {
		return this.liveStatusCode;
	}

	public void setLiveStatusCode(String liveStatusCode) {
		if(liveStatusCode != null){
			this.liveStatusCode = liveStatusCode.replaceAll("\\s", "");
		}else{
			this.liveStatusCode = liveStatusCode;
		}
	}

	@Column(name = "edu_level", nullable = false, length = 20)
	public String getEduLevel() {
		return this.eduLevel;
	}

	public void setEduLevel(String eduLevel) {
		if(eduLevel != null){
			this.eduLevel = eduLevel.replaceAll("\\s", "");
		}else{
			this.eduLevel = eduLevel;
		}
	}

	@Column(name = "edu_level_code", nullable = false, length = 20)
	public String getEduLevelCode() {
		return this.eduLevelCode;
	}

	public void setEduLevelCode(String eduLevelCode) {
		if(eduLevelCode != null){
			this.eduLevelCode = eduLevelCode.replaceAll("\\s", "");
		}else{
			this.eduLevelCode = eduLevelCode;
		}
	}

	@Column(name = "province", nullable = false, length = 20)
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		if(province != null){
			this.province = province.replaceAll("\\s", "");
		}else{
			this.province = province;
		}
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		if(city != null){
			this.city = city.replaceAll("\\s", "");
		}else{
			this.city = city;
		}
	}

	@Column(name = "family_addr", nullable = false, length = 100)
	public String getFamilyAddr() {
		return this.familyAddr;
	}

	public void setFamilyAddr(String familyAddr) {
		if(familyAddr != null){
			this.familyAddr = familyAddr.replaceAll("\\s", "");
		}else{
			this.familyAddr = familyAddr;
		}
	}

	@Column(name = "family_phone", nullable = false, length = 100)
	public String getFamilyPhone() {
		return familyPhone;
	}

	public void setFamilyPhone(String familyPhone) {
		if(familyPhone != null){
			this.familyPhone = familyPhone.replaceAll("\\s", "");
		}else{
			this.familyPhone = familyPhone;
		}
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		if(email != null){
			this.email = email.replaceAll("\\s", "");
		}else{
			this.email = email;
		}
	}

	@Column(name = "marr_status", nullable = false, length = 20)
	public String getMarrStatus() {
		return this.marrStatus;
	}

	public void setMarrStatus(String marrStatus) {
		if(marrStatus != null){
			this.marrStatus = marrStatus.replaceAll("\\s", "");
		}else{
			this.marrStatus = marrStatus;
		}
	}

	@Column(name = "marr_status_code", nullable = false, length = 20)
	public String getMarrStatusCode() {
		return this.marrStatusCode;
	}

	public void setMarrStatusCode(String marrStatusCode) {
		if(marrStatusCode != null){
			this.marrStatusCode = marrStatusCode.replaceAll("\\s", "");
		}else{
			this.marrStatusCode = marrStatusCode;
		}
	}

	@Column(name = "spouse_name", length = 10)
	public String getSpouseName() {
		return this.spouseName;
	}

	public void setSpouseName(String spouseName) {
		if(spouseName != null){
			this.spouseName = spouseName.replaceAll("\\s", "");
		}else{
			this.spouseName = spouseName;
		}
	}

	@Column(name = "spouse_cert_type", length = 10)
	public String getSpouseCertType() {
		return this.spouseCertType;
	}

	public void setSpouseCertType(String spouseCertType) {
		if(spouseCertType != null){
			this.spouseCertType = spouseCertType.replaceAll("\\s", "");
		}else{
			this.spouseCertType = spouseCertType;
		}
	}

	@Column(name = "spouse_cert_id", length = 18)
	public String getSpouseCertId() {
		return this.spouseCertId;
	}

	public void setSpouseCertId(String spouseCertId) {
		if(spouseCertId != null){
			this.spouseCertId = spouseCertId.replaceAll("\\s", "");
		}else{
			this.spouseCertId = spouseCertId;
		}
	}

	@Column(name = "spouse_phone", length = 11)
	public String getSpousePhone() {
		return this.spousePhone;
	}

	public void setSpousePhone(String spousePhone) {
		if(spousePhone != null){
			this.spousePhone = spousePhone.replaceAll("\\s", "");
		}else{
			this.spousePhone = spousePhone;
		}
	}

	@Column(name = "spouse_annual_income", length = 20)
	public String getSpouseAnnualIncome() {
		return this.spouseAnnualIncome;
	}

	public void setSpouseAnnualIncome(String spouseAnnualIncome) {
		if(spouseAnnualIncome != null){
			this.spouseAnnualIncome = spouseAnnualIncome.replaceAll("\\s", "");
		}else{
			this.spouseAnnualIncome = spouseAnnualIncome;
		}
	}

	@Column(name = "spouse_annual_income_code", length = 20)
	public String getSpouseAnnualIncomeCode() {
		return this.spouseAnnualIncomeCode;
	}

	public void setSpouseAnnualIncomeCode(String spouseAnnualIncomeCode) {
		if(spouseAnnualIncomeCode != null){
			this.spouseAnnualIncomeCode = spouseAnnualIncomeCode.replaceAll("\\s", "");
		}else{
			this.spouseAnnualIncomeCode = spouseAnnualIncomeCode;
		}
	}

	@Column(name = "spouse_income_from", length = 20)
	public String getSpouseIncomeFrom() {
		return spouseIncomeFrom;
	}

	public void setSpouseIncomeFrom(String spouseIncomeFrom) {
		this.spouseIncomeFrom = spouseIncomeFrom;
	}

	@Column(name = "spouse_income_from_code", length = 20)
	public String getSpouseIncomeFromCode() {
		return spouseIncomeFromCode;
	}

	public void setSpouseIncomeFromCode(String spouseIncomeFromCode) {
		this.spouseIncomeFromCode = spouseIncomeFromCode;
	}

	@Column(name = "spouse_work_unit", length = 60)
	public String getSpouseWorkUnit() {
		return spouseWorkUnit;
	}

	public void setSpouseWorkUnit(String spouseWorkUnit) {
		if(spouseWorkUnit !=null){
			this.spouseWorkUnit = spouseWorkUnit.replaceAll("\\s", "");
		}else{
			this.spouseWorkUnit = spouseWorkUnit;
		}
	}

	@Column(name = "contact_relation", length = 20)
	public String getContactRelation() {
		return this.contactRelation;
	}

	public void setContactRelation(String contactRelation) {
		if(contactRelation !=null){
			this.contactRelation = contactRelation.replaceAll("\\s", "");
		}else{
			this.contactRelation = contactRelation;
		}
	}

	@Column(name = "contact_relation_code", length = 20)
	public String getContactRelationCode() {
		return this.contactRelationCode;
	}

	public void setContactRelationCode(String contactRelationCode) {
		this.contactRelationCode = contactRelationCode;
	}

	@Column(name = "contact_name", length = 10)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		if(contactName != null){
			this.contactName = contactName.replaceAll("\\s", "");
		}else{
			this.contactName = contactName;
		}
	}

	@Column(name = "contact_cert_type", length = 20)
	public String getContactCertType() {
		return this.contactCertType;
	}

	public void setContactCertType(String contactCertType) {
		if(contactCertType != null){
			this.contactCertType = contactCertType.replaceAll("\\s", "");
		}else{
			this.contactCertType = contactCertType;
		}
	}

	@Column(name = "contact_cert_id", length = 20)
	public String getContactCertId() {
		return this.contactCertId;
	}

	public void setContactCertId(String contactCertId) {
		if(contactCertId != null){
			this.contactCertId = contactCertId.replaceAll("\\s", "");
		}else{
			this.contactCertId = contactCertId;
		}
	}

	@Column(name = "contact_phone", length = 11)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		if(contactPhone != null){
			this.contactPhone = contactPhone.replaceAll("\\s", "");
		}else{
			this.contactPhone = contactPhone;
		}
	}
}
