package com.kpleasing.wxss.entity;
// Generated 2018-3-27 9:41:18 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbProvince generated by hbm2java
 */
@Entity
@Table(name = "tb_province", catalog = "wxss")
public class Province implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 4740732585410283439L;
	private Integer id;
	private String provinceCode;
	private String provinceName;
	private String abbreviated;

	public Province() {
	}

	public Province(String provinceCode, String provinceName, String abbreviated) {
		this.provinceCode = provinceCode;
		this.provinceName = provinceName;
		this.abbreviated = abbreviated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "province_code", nullable = false, length = 6)
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "province_name", nullable = false, length = 20)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "abbreviated", nullable = false, length = 2)
	public String getAbbreviated() {
		return this.abbreviated;
	}

	public void setAbbreviated(String abbreviated) {
		this.abbreviated = abbreviated;
	}
}
