package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbScheme generated by hbm2java
 */
/**
 * @author zhangxing
 *
 */
@Entity
@Table(name = "r_sp_car", catalog = "wxss")
public class RSpCar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**	 * 	 */
	
	private Integer id;
	private int bpId;
	private int modelId;
	private String modelLogo;
	private Date createAt;
	private String enabledFlag;
	
	public RSpCar() {
	}


	public RSpCar(Integer id, int bpId, int modelId, String modelLogo, Date createAt, String enabledFlag) {
		super();
		this.id = id;
		this.bpId = bpId;
		this.modelId = modelId;
		this.modelLogo = modelLogo;
		this.createAt = createAt;
		this.enabledFlag = enabledFlag;
	}


	@Override
	public String toString() {
		return "SpCarModel [id=" + id + ", bpId=" + bpId + ", modelId=" + modelId + ", ModelLogo=" + modelLogo
				+ ", createAt=" + createAt + ", enabledFlag=" + enabledFlag + "]";
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "bp_id")
	public int getBpId() {
		return bpId;
	}

	public void setBpId(int bpId) {
		this.bpId = bpId;
	}

	@Column(name = "model_id")
	public int getModelId() {
		return modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@Column(name = "model_logo")
	public String getModelLogo() {
		return modelLogo;
	}
 
	public void setModelLogo(String modelLogo) {
		this.modelLogo = modelLogo;
	}

	@Column(name = "create_at")
	public Date getCreateAt() {
		return createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "enabled_flag")
	public String getEnabledFlag() {
		return enabledFlag;
	}

	public void setEnabledFlag(String enabledFlag) {
		this.enabledFlag = enabledFlag;
	}
	
}
