package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbScheme generated by hbm2java
 */
@Entity
@Table(name = "tb_scheme", catalog = "wxss")
public class Scheme implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 3749762858629096387L;
	private Integer id;
	private int planId;
	private String planDesc;
	private int modelId;
	private String leaseItemAmount;
	private String downpaymentAmount;
	private String depositAmount;
	private String purchaseTax;
	private String insuranceFeeFinancing;
	private String carPlateFee;
	private String gpsFee;
	private String taxinsurance;
	private String pckprice;
	private String leaseTimes;
	private String planType;
	private String rental;
	private String intRate;
	private String rental112;
	private String rental1348;
	private String buyoutAmount;
	private String validDateFrom;
	private String validDateTo;
	private Date createAt;
	private Date updateAt;
	private String remark;

	public Scheme() {
	}

	public Scheme(int planId, int modelId, Date createAt) {
		this.planId = planId;
		this.modelId = modelId;
		this.createAt = createAt;
	}

	public Scheme(int planId, String planDesc, int modelId, String leaseItemAmount, String downpaymentAmount,
			String depositAmount, String purchaseTax, String insuranceFeeFinancing, String carPlateFee, String gpsFee,
			String taxinsurance, String pckprice, String leaseTimes, String planType, String rental, String intRate,
			String rental112, String rental1348, String buyoutAmount, String validDateFrom, String validDateTo,
			Date createAt, Date updateAt, String remark) {
		this.planId = planId;
		this.planDesc = planDesc;
		this.modelId = modelId;
		this.leaseItemAmount = leaseItemAmount;
		this.downpaymentAmount = downpaymentAmount;
		this.depositAmount = depositAmount;
		this.purchaseTax = purchaseTax;
		this.insuranceFeeFinancing = insuranceFeeFinancing;
		this.carPlateFee = carPlateFee;
		this.gpsFee = gpsFee;
		this.taxinsurance = taxinsurance;
		this.pckprice = pckprice;
		this.leaseTimes = leaseTimes;
		this.planType = planType;
		this.rental = rental;
		this.intRate = intRate;
		this.rental112 = rental112;
		this.rental1348 = rental1348;
		this.buyoutAmount = buyoutAmount;
		this.validDateFrom = validDateFrom;
		this.validDateTo = validDateTo;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "plan_id", nullable = false)
	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	@Column(name = "plan_desc", length = 20)
	public String getPlanDesc() {
		return this.planDesc;
	}

	public void setPlanDesc(String planDesc) {
		this.planDesc = planDesc;
	}

	@Column(name = "model_id", nullable = false)
	public int getModelId() {
		return this.modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@Column(name = "lease_item_amount", length = 20)
	public String getLeaseItemAmount() {
		return this.leaseItemAmount;
	}

	public void setLeaseItemAmount(String leaseItemAmount) {
		this.leaseItemAmount = leaseItemAmount;
	}

	@Column(name = "downpayment_amount", length = 20)
	public String getDownpaymentAmount() {
		return this.downpaymentAmount;
	}

	public void setDownpaymentAmount(String downpaymentAmount) {
		this.downpaymentAmount = downpaymentAmount;
	}

	@Column(name = "deposit_amount", length = 20)
	public String getDepositAmount() {
		return this.depositAmount;
	}

	public void setDepositAmount(String depositAmount) {
		this.depositAmount = depositAmount;
	}

	@Column(name = "purchase_tax", length = 20)
	public String getPurchaseTax() {
		return this.purchaseTax;
	}

	public void setPurchaseTax(String purchaseTax) {
		this.purchaseTax = purchaseTax;
	}

	@Column(name = "insurance_fee_financing", length = 20)
	public String getInsuranceFeeFinancing() {
		return this.insuranceFeeFinancing;
	}

	public void setInsuranceFeeFinancing(String insuranceFeeFinancing) {
		this.insuranceFeeFinancing = insuranceFeeFinancing;
	}

	@Column(name = "car_plate_fee", length = 20)
	public String getCarPlateFee() {
		return this.carPlateFee;
	}

	public void setCarPlateFee(String carPlateFee) {
		this.carPlateFee = carPlateFee;
	}

	@Column(name = "gps_fee", length = 20)
	public String getGpsFee() {
		return this.gpsFee;
	}

	public void setGpsFee(String gpsFee) {
		this.gpsFee = gpsFee;
	}

	@Column(name = "taxinsurance", length = 20)
	public String getTaxinsurance() {
		return this.taxinsurance;
	}

	public void setTaxinsurance(String taxinsurance) {
		this.taxinsurance = taxinsurance;
	}

	@Column(name = "pckprice", length = 20)
	public String getPckprice() {
		return this.pckprice;
	}

	public void setPckprice(String pckprice) {
		this.pckprice = pckprice;
	}

	@Column(name = "lease_times", length = 20)
	public String getLeaseTimes() {
		return this.leaseTimes;
	}

	public void setLeaseTimes(String leaseTimes) {
		this.leaseTimes = leaseTimes;
	}

	@Column(name = "plan_type", length = 20)
	public String getPlanType() {
		return this.planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	@Column(name = "rental", length = 20)
	public String getRental() {
		return this.rental;
	}

	public void setRental(String rental) {
		this.rental = rental;
	}

	@Column(name = "int_rate", length = 20)
	public String getIntRate() {
		return this.intRate;
	}

	public void setIntRate(String intRate) {
		this.intRate = intRate;
	}

	@Column(name = "rental_1_12", length = 20)
	public String getRental112() {
		return this.rental112;
	}

	public void setRental112(String rental112) {
		this.rental112 = rental112;
	}

	@Column(name = "rental_13_48", length = 20)
	public String getRental1348() {
		return this.rental1348;
	}

	public void setRental1348(String rental1348) {
		this.rental1348 = rental1348;
	}

	@Column(name = "buyout_amount", length = 20)
	public String getBuyoutAmount() {
		return this.buyoutAmount;
	}

	public void setBuyoutAmount(String buyoutAmount) {
		this.buyoutAmount = buyoutAmount;
	}

	@Column(name = "valid_date_from", length = 20)
	public String getValidDateFrom() {
		return this.validDateFrom;
	}

	public void setValidDateFrom(String validDateFrom) {
		this.validDateFrom = validDateFrom;
	}

	@Column(name = "valid_date_to", length = 20)
	public String getValidDateTo() {
		return this.validDateTo;
	}

	public void setValidDateTo(String validDateTo) {
		this.validDateTo = validDateTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", nullable = false, length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
