package com.kpleasing.wxss.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbSecurityKey generated by hbm2java
 */
@Entity
@Table(name = "tb_security_key", catalog = "wxss")
public class SecurityKey implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 4764033196454495328L;
	private Integer id;
	private String apiName;
	private String sysName;
	private String sysCode;
	private String signKey;

	public SecurityKey() {
	}

	public SecurityKey(String apiName, String sysName, String sysCode, String signKey) {
		this.apiName = apiName;
		this.sysName = sysName;
		this.sysCode = sysCode;
		this.signKey = signKey;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "api_name", nullable = false, length = 32)
	public String getApiName() {
		return this.apiName;
	}

	public void setApiName(String apiName) {
		this.apiName = apiName;
	}

	@Column(name = "sys_name", nullable = false, length = 20)
	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	@Column(name = "sys_code", nullable = false, length = 20)
	public String getSysCode() {
		return this.sysCode;
	}

	public void setSysCode(String sysCode) {
		this.sysCode = sysCode;
	}

	@Column(name = "sign_key", nullable = false, length = 32)
	public String getSignKey() {
		return this.signKey;
	}

	public void setSignKey(String signKey) {
		this.signKey = signKey;
	}

}
