package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSpInfo generated by hbm2java
 */
@Entity
public class SpCar {
 
	/** * */
	private static final long serialVersionUID = -1565058961434435603L;
	private String brand;
	private String series;
	private Integer modelId;
	private String model;
	private String seriesLogo;
	private String description1;
	private String description2;
	private String purchaseTax;
	private String insuranceFeeFinancing;
	private String msrp;
	public SpCar() {
	}

	public String getMsrp() {
		return msrp;
	}

	public void setMsrp(String msrp) {
		this.msrp = msrp;
	}

	public SpCar(String brand, String series, Integer modelId, String model, String seriesLogo, String description1,
			String description2) {
		this.brand = brand;
		this.series = series;
		this.modelId = modelId;
		this.model = model;
		this.seriesLogo = seriesLogo;
		this.description1 = description1;
		this.description1 = description2;
	}
	
	public SpCar(String brand, String series, Integer modelId, String model, String seriesLogo, String description1,
			String description2,String purchaseTax,String insuranceFeeFinancing) {
		this.brand = brand;
		this.series = series;
		this.modelId = modelId;
		this.model = model;
		this.seriesLogo = seriesLogo;
		this.description1 = description1;
		this.description1 = description2;
		this.purchaseTax=purchaseTax;
		this.insuranceFeeFinancing=insuranceFeeFinancing;
	}
	
	public SpCar(String brand, String series, Integer modelId, String model, String seriesLogo, String description1,
			String description2,String purchaseTax,String insuranceFeeFinancing,String msrp) {
		this.brand = brand;
		this.series = series;
		this.modelId = modelId;
		this.model = model;
		this.seriesLogo = seriesLogo;
		this.description1 = description1;
		this.description1 = description2;
		this.purchaseTax=purchaseTax;
		this.insuranceFeeFinancing=insuranceFeeFinancing;
		this.msrp=msrp;
	}
	
	

	@Override
	public String toString() {
		return "SpCar [brand=" + brand + ", series=" + series + ", modelId=" + modelId + ", model=" + model
				+ ", seriesLogo=" + seriesLogo + ", description1=" + description1 + ", description2=" + description2
				+ ", purchaseTax=" + purchaseTax + ", insuranceFeeFinancing=" + insuranceFeeFinancing + "]";
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getSeries() {
		return series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	public Integer getModelId() {
		return modelId;
	}

	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getPurchaseTax() {
		return purchaseTax;
	}

	public void setPurchaseTax(String purchaseTax) {
		this.purchaseTax = purchaseTax;
	}

	public String getInsuranceFeeFinancing() {
		return insuranceFeeFinancing;
	}

	public void setInsuranceFeeFinancing(String insuranceFeeFinancing) {
		this.insuranceFeeFinancing = insuranceFeeFinancing;
	}

	public String getSeriesLogo() {
		return seriesLogo;
	}

	public void setSeriesLogo(String seriesLogo) {
		this.seriesLogo = seriesLogo;
	}

	public String getDescription1() {
		return description1;
	}

	public void setDescription1(String description1) {
		this.description1 = description1;
	}

	public String getDescription2() {
		return description2;
	}

	public void setDescription2(String description2) {
		this.description2 = description2;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
