package com.kpleasing.wxss.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSpInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_sp_info", catalog = "wxss")
public class SpInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = -1565058961434435603L;
	private Integer id;
	private int bpId;
	private String bpCode;
	private String bpName;
	private String organizationCode;
	private String province;
	private String city;
	private String imageUrl;
	private byte enabledFlag;
	private Date createAt;
	private Date updateAt;
	private String spLogo;
	private String cellPhone;
	
	
	

	@Override
	public String toString() {
		return "SpInfo [id=" + id + ", bpId=" + bpId + ", bpCode=" + bpCode + ", bpName=" + bpName
				+ ", organizationCode=" + organizationCode + ", province=" + province + ", city=" + city + ", imageUrl="
				+ imageUrl + ", enabledFlag=" + enabledFlag + ", createAt=" + createAt + ", updateAt=" + updateAt + "]";
	}

	public SpInfo() {
	}

	public SpInfo(int bpId, Date createAt) {
		this.bpId = bpId;
		this.createAt = createAt;
	}


	public SpInfo(int bpId, String bpCode, String bpName, String organizationCode, String province, String city,
			String imageUrl,byte enabledFlag, Date createAt, Date updateAt, String spLogo,String cellPhone) {
		this.bpId = bpId;
		this.bpCode = bpCode;
		this.bpName = bpName;
		this.organizationCode = organizationCode;
		this.province = province;
		this.city = city;
		this.imageUrl = imageUrl;
		this.enabledFlag = enabledFlag;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.spLogo = spLogo;
		this.cellPhone = cellPhone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bp_id", nullable = false)
	public int getBpId() {
		return this.bpId;
	}

	public void setBpId(int bpId) {
		this.bpId = bpId;
	}

	@Column(name = "bp_code", length = 20)
	public String getBpCode() {
		return this.bpCode;
	}

	public void setBpCode(String bpCode) {
		this.bpCode = bpCode;
	}

	@Column(name = "bp_name", length = 60)
	public String getBpName() {
		return this.bpName;
	}

	public void setBpName(String bpName) {
		this.bpName = bpName;
	}

	@Column(name = "organization_code", length = 20)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "province", length = 20)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", nullable = false, length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "enabled_flag", nullable = false)
	public byte getEnabledFlag() {
		return this.enabledFlag;
	}

	public void setEnabledFlag(byte enabledFlag) {
		this.enabledFlag = enabledFlag;
	}
	
	@Column(name = "sp_logo")
	public String getSpLogo() {
		return this.spLogo;
	}

	public void setSpLogo(String spLogo) {
		this.spLogo = spLogo;
	}
	
	@Column(name = "cell_phone")
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

}
