package com.kpleasing.wxss.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorkInfo generated by hbm2java
 */
@Entity
@Table(name = "tb_work_info")
public class WorkInfo implements java.io.Serializable {

	/**	 * 	 */
	private static final long serialVersionUID = 7362601929008300166L;
	private int userId;
	private String workUnit;
	private String entryYear;
	private String position;
	private String unitTel;
	private String incomeStatus;
	private String incomeStatusCode;
	private String incomeFrom;
	private String incomeFromCode;
	private String annualIncome;
	private String workAddr;
	private String workYear;

	public WorkInfo() {
	}

	public WorkInfo(int userId, String workUnit, String entryYear, String position, String unitTel, String incomeStatus,
			String incomeFrom,String annualIncome,String workAddr,String workYear) {
		this.userId = userId;
		this.workUnit = workUnit;
		this.entryYear = entryYear;
		this.position = position;
		this.unitTel = unitTel;
		this.incomeStatus = incomeStatus;
		this.incomeFrom = incomeFrom;
		this.annualIncome = annualIncome;
		this.workAddr = workAddr;
		this.workYear = workYear;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "work_unit", nullable = false, length = 60)
	public String getWorkUnit() {
		return this.workUnit;
	}

	public void setWorkUnit(String workUnit) {
		if(workUnit != null){
			this.workUnit = workUnit.replaceAll("\\s", "");
		}else{
			this.workUnit = workUnit;
		}
	}

	@Column(name = "entry_year", nullable = false, length = 20)
	public String getEntryYear() {
		return this.entryYear;
	}

	public void setEntryYear(String entryYear) {
		if(entryYear != null){
			this.entryYear = entryYear.replaceAll("\\s", "");
		}else{
			this.entryYear = entryYear;
		}
	}

	@Column(name = "position", nullable = false, length = 20)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		if(position != null){
			this.position = position.replaceAll("\\s", "");
		}else{
			this.position = position;
		}
	}

	@Column(name = "unit_tel", nullable = false, length = 20)
	public String getUnitTel() {
		return this.unitTel;
	}

	public void setUnitTel(String unitTel) {
		if(unitTel != null){
			this.unitTel = unitTel.replaceAll("\\s", "");
		}else{
			this.unitTel = unitTel;
		}
	}

	@Column(name = "income_status", nullable = false, length = 20)
	public String getIncomeStatus() {
		return this.incomeStatus;
	}

	public void setIncomeStatus(String incomeStatus) {
		if(incomeStatus != null){
			this.incomeStatus = incomeStatus.replaceAll("\\s", "");
		}else{
			this.incomeStatus = incomeStatus;
		}
	}

	@Column(name = "income_status_code", nullable = false, length = 20)
	public String getIncomeStatusCode() {
		return incomeStatusCode;
	}

	public void setIncomeStatusCode(String incomeStatusCode) {
		if(incomeStatusCode != null){
			this.incomeStatusCode = incomeStatusCode.replaceAll("\\s", "");
		}else{
			this.incomeStatusCode = incomeStatusCode;
		}
	}

	@Column(name = "income_from", nullable = false, length = 20)
	public String getIncomeFrom() {
		return this.incomeFrom;
	}

	public void setIncomeFrom(String incomeFrom) {
		if(incomeFrom != null){
			this.incomeFrom = incomeFrom.replaceAll("\\s", "");
		}else{
			this.incomeFrom = incomeFrom;
		}
	}

	@Column(name = "income_from_code", nullable = false, length = 20)
	public String getIncomeFromCode() {
		return incomeFromCode;
	}

	public void setIncomeFromCode(String incomeFromCode) {
		if(incomeFromCode != null){
			this.incomeFromCode = incomeFromCode.replaceAll("\\s", "");
		}else{
			this.incomeFromCode = incomeFromCode;
		}
	}

	@Column(name = "annual_income", nullable = false, length = 20)
	public String getAnnualIncome() {
		return annualIncome;
	}

	public void setAnnualIncome(String annualIncome) {
		if(annualIncome != null){
			this.annualIncome = annualIncome.replaceAll("\\s", "");
		}else{
			this.annualIncome = annualIncome;
		}
	}

	@Column(name = "work_addr", nullable = false, length = 255)
	public String getWorkAddr() {
		return workAddr;
	}

	public void setWorkAddr(String workAddr) {
		if(workAddr != null){
			this.workAddr = workAddr.replaceAll("\\s", "");
		}else{
			this.workAddr = workAddr;
		}
	}

	@Column(name = "work_year", nullable = false, length = 10)
	public String getWorkYear() {
		return workYear;
	}

	public void setWorkYear(String workYear) {
		if(workYear != null){
			this.workYear = workYear.replaceAll("\\s", "");
		}else{
			this.workYear = workYear;
		}
	}
}
